### ISSUE TITLE
incorporate external resources

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/IBL-to-nwb#50]
@CodyCBakerPhD could you try adding some external resources to the conversion pipeline? See example code [here](https://github.com/catalystneuro/neuroconv/issues/333)

**Comment by CodyCBakerPhD** [comment]
Sure, once I get back from break

**Comment by CodyCBakerPhD** [comment]
The files do not have experimenters (they're call on that - no info available for associating individual sessions and way too many total authors to put in at the file level)

But I can for sure attach species

Brain regions... will be interesting

Allen Mouse Brain Atlas I might be able to do but it will take some time to look up all the UBERONS (there are a lot of brain areas after all...) - do you know of a nice API for doing that auto lookup or is that part of what we need to build?
