### ISSUE TITLE
CN TODO: Correct raw timestamps

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/IBL-to-nwb#63]
SpikeSortingLoader has a method that gives a mapping from frame indices in raw recording to timestamps used for spike sorting, etc.

Maybe Mayo can send explicit code

**Comment by CodyCBakerPhD** [comment]
@mayofaulkner Would you be so kind as to copy/paste a code segment here showing how to get the synchronized frame to global timestamp mapping?

**Comment by mayofaulkner** [comment]
Here is a snippet that shows how you can get the raw data timestamps
```
from brainbox.io.one import SpikeSortingLoader
from one.api import ONE
import numpy as np
one = ONE()
ssl = SpikeSortingLoader(pid=pid, one=one)
sr_ap = ssl.raw_electrophysiology(band="ap", stream=True)
sr_times = ssl.samples2times(np.arange(0, sr_ap.ns), direction='forward')
```
