### ISSUE TITLE
Is parallel mode desired?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/IBL-to-nwb#81]
A question for @grg2rsr as I clean up and update the various conversion scripts

For any script dealing with iteration over multiple sessions, do you still want that to be parallelized?

**Comment by grg2rsr** [comment]
no I don't think so. Do you think it will have any performance gains over submitting many jobs to the cluster and letting the job scheduler take care of it. Especially since this is going to be a "one time run" (or few times), I don't think speed is super critical

**Comment by CodyCBakerPhD** [comment]
> Do you think it will have any performance gains over submitting many jobs to the cluster and letting the job scheduler take care of it?

That is effectively the same thing, though probably not maximizing potential I/O usage per 'job'

Should be even faster overall though if the cluster has a large number of nodes

So I will let you handle it by designing bash scripts that run the conversion on a particular job ID and remove the current parallel scripts
